# Generated by Django 3.1.4 on 2020-12-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_pizza', models.CharField(max_length=7)),
                ('size', models.CharField(max_length=10)),
                ('toppings', models.CharField(max_length=15)),
            ],
        ),
    ]
