# Generated by Django 3.1.4 on 2020-12-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0002_auto_20201206_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzamodel',
            name='type_of_pizza',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('SQUARE', 'Square')], max_length=7),
        ),
    ]
