# Generated by Django 3.1.4 on 2020-12-06 12:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0003_auto_20201206_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppings', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), size=None)),
                ('size_of_pizza', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
            ],
        ),
        migrations.AlterField(
            model_name='pizzamodel',
            name='size',
            field=models.CharField(max_length=20),
        ),
    ]
