# Generated by Django 3.1.4 on 2020-12-06 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0004_auto_20201206_1823'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PizzaLayout',
        ),
    ]
