# Generated by Django 3.1.4 on 2020-12-06 13:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0005_delete_pizzalayout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzamodel',
            name='size',
            field=models.CharField(choices=[('SMALL 7"\n', 'Small 7"\n'), ('MEDIUM 9"\n', 'Medium 9"\n'), ('LARGE 11"\n', 'Large 11"\n'), ('LARGE 18"', 'Large 18"')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pizzamodel',
            name='toppings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), choices=[('JALAPENO\n', 'Jalapeno\n'), ('ONION\n', 'Onion\n'), ('TOMATO\n', 'Tomato\n'), ('CAPSICUM\n', 'Capsicum\n'), ('CORN\n', 'Corn\n')], size=None),
        ),
    ]
