# Generated by Django 3.1.4 on 2020-12-06 14:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0007_auto_20201206_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topp', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='pizzamodel',
            name='size',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pizzamodel',
            name='toppings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), size=None),
        ),
    ]
